layout_spectrum: 0.6057724262426358
typography_spectrum: 0.6295546944850668
color:
  brandStrength: 0.42114052638752697
  lightness: 0.9462957771887799
  saturation: 0.8784467346291288
  rhythmicContrast: 0.9700736757093985
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
github: true
name: caliper
navigation:
  - name: Nav 1
    id: 8d1af655-f2de-41c5-b017-f1fed5ac2e15
    type: content
  - name: Nav2
    id: b510b9e4-2913-41dc-9293-bf9656d4be65
    type: content
  - name: Nav 3
    id: 87464034-c6cf-4144-8a9d-4d0f3182be4e
    type: content
  - name: Nav 4
    id: dc906dee-c417-43b5-9235-e1f4f31133b5
    type: content
title: Caliper
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8165eb8-968a-4f81-9cf3-1a146fe6bb49.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8165eb8-968a-4f81-9cf3-1a146fe6bb49.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Testing content sharing
purpose:
  - type: contact
    url: 'mailto:gabithume@gmail.com'
    label: Contact me
