typography_spectrum: 0.9401997134768136
color:
  brandStrength: 0.6884007840331571
  lightness: 1
  saturation: 0.42967043834867524
  rhythmicContrast: 1
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.7165732007652594
name: caliper
navigation:
  - name: Testing nav
    id: acb628c5-2d27-4aab-8946-0e6caac6f475
    type: content
title: Caliper
content: []
description: ''
