typography_spectrum: 0.6207597680669278
color:
  brandStrength: 0.7136747887855082
  lightness: 0.8227202621567994
  saturation: 0.688099739580406
  rhythmicContrast: 0.9796803947610061
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.14869707540276988
name: caliper
navigation:
  - name: Nav 1
    id: 8d1af655-f2de-41c5-b017-f1fed5ac2e15
    type: content
  - name: Nav2
    id: b510b9e4-2913-41dc-9293-bf9656d4be65
    type: content
  - name: Nav 3
    id: 87464034-c6cf-4144-8a9d-4d0f3182be4e
    type: content
title: Caliper
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8165eb8-968a-4f81-9cf3-1a146fe6bb49.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8165eb8-968a-4f81-9cf3-1a146fe6bb49.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Testing content sharing
purpose: []
